"""Scorecard: every pretrained policy through the same tests on the same robot, in parallel on CPU.

  docker run --rm -v $PWD:/workspace/g1_stairs g1-arena -m arena.scorecard --workers 14

Locomotion policies (arena.policies.REGISTRY):
  flat        walk schedule (stand, 0.5 and 1.0 m/s, walk + turn, sidestep, stop), 20 s, G1 + Dex3 hands
  no_hands    same on the G1 29-DoF model without hands
  rough       same on 6 cm random terrain
  arms        same on flat, with the arms the policy does not control swinging and reaching (0.5 Hz)
  push        walking at 0.5 m/s, lateral pelvis pushes of 100..1000 N for 0.1 s every 3 s
  stairs      10 steps up (15 cm), 1.2 m platform, 10 down, at 0.6 m/s, 20 s
  crouch      pelvis height commands 0.62 / 0.52 / 0.70 m (policies with a height input)
Trackers (arena.policies.TRACKERS): every clip of arena.track.clips().

Writes output/scorecard.json and docs/SCORECARD.md.
"""
from __future__ import annotations

import argparse
import json
import os

os.environ.setdefault("OMP_NUM_THREADS", "1")

import numpy as np  # noqa: E402

from arena import run as R  # noqa: E402
from arena.world import G1_29_XML, REPO  # noqa: E402

R.PUSHES[:] = [(3.0 + 3 * i, 0.1, np.array([0.0, (-1) ** i * f, 0.0])) for i, f in
               enumerate(range(100, 1001, 100))]
HEIGHT_POLICIES = {"agile_vel_height", "gr00t_wbc", "sonic", "g1_body"}
TESTS = {  # name: run() kwargs
    "flat": dict(terrain="flat", schedule="walk", seconds=20),
    "no_hands": dict(terrain="flat", schedule="walk", seconds=20, robot_xml=G1_29_XML),
    "rough": dict(terrain="rough", schedule="walk", seconds=20),
    "arms": dict(terrain="flat", schedule="walk", seconds=20, arms=True),
    "push": dict(terrain="flat", schedule="push", seconds=33),
    "stairs": dict(terrain="stairs", schedule="stairs", seconds=20),
    "crouch": dict(terrain="flat", schedule="crouch", seconds=15),
}


def jobs():
    from arena.policies import REGISTRY, TRACKERS, make
    from arena.track import clips
    out = []
    for p in REGISTRY:
        owns_arms = all(j in make(p).joints for j in R.ARM_JOINTS)
        for t in TESTS:
            if t == "crouch" and p not in HEIGHT_POLICIES:
                continue
            if t == "arms" and owns_arms:
                continue
            out.append(("loco", p, t))
    for p in TRACKERS:
        for c in clips():
            out.append(("track", p, c))
    return out


def work(job):
    kind, p, t = job
    try:
        if kind == "loco":
            return {"kind": kind, "test": t, **R.run(p, **TESTS[t])}
        from arena.track import load_clip, track
        return {"kind": kind, "test": t, **track(p, load_clip(t))}
    except Exception as e:           # a policy that cannot run a test (e.g. needs the hand joints) is reported
        return {"kind": kind, "test": t, "policy": p, "error": repr(e)[:200]}


def _f(x, d=2):
    return "-" if x is None or (isinstance(x, float) and np.isnan(x)) else f"{x:.{d}f}"


def markdown(results):
    from arena.policies import REGISTRY, TRACKERS
    by = {(r["policy"], r["test"]): r for r in results}
    L = ["# Scorecard", "",
         "Generated by `python -m arena.scorecard` (MuJoCo 3.6, G1 29-DoF + Dex3 unless noted). Each policy runs through"
         " its adapter with the PD gains it was trained with; `arena/check_adapters.py` shows each adapter matches"
         " its repo (SONIC: C++ reference only, validated by tracking). Velocity errors are mean |measured - command|"
         " in the body frame, skipping 1.5 s after each command change. `X` = fell (time in s).", "",
         "## Locomotion", "",
         "| policy | flat vx/wz err | no hands vx err | rough vx err | arms waving vx err | max push survived [N] "
         "| stairs | crouch height err [m] (lowest) |",
         "|---|---|---|---|---|---|---|---|"]

    def cell(p, t, key, d=3):
        r = by.get((p, t))
        if r is None:
            return "n/a"
        if "error" in r:
            return "needs hands" if "hand" in r["error"] else "error"
        if r["fell"] and t != "push":
            return f"X {r['fall_t']:.1f}"
        return _f(r.get(key), d)

    for p in REGISTRY:
        f = by.get((p, "flat"), {})
        flat = cell(p, "flat", "vx_err") if f.get("fell") or "error" in f else \
            f"{_f(f.get('vx_err'), 3)} / {_f(f.get('wz_err'), 3)}"
        s = by.get((p, "stairs"))
        stairs = "n/a" if s is None else "error" if "error" in s else \
            ("crossed" if s.get("crossed") else
             (f"top, X {s['fall_t']:.1f}" if s["fell"] else "top, not down") if s.get("reached_top") else
             f"X {s['fall_t']:.1f}" if s["fell"] else "stuck")
        c = by.get((p, "crouch"))
        crouch = "n/a" if c is None else "error" if "error" in c else f"X {c['fall_t']:.1f}" if c["fell"] else \
            f"{_f(c.get('height_err'), 3)} ({_f(c.get('min_height'))})"
        pu = by.get((p, "push"), {})
        push = "error" if "error" in pu else _f(pu.get("max_push_N"), 0)
        L.append(f"| {p} | {flat} | {cell(p, 'no_hands', 'vx_err')} | {cell(p, 'rough', 'vx_err')} | "
                 f"{cell(p, 'arms', 'vx_err')} | {push} | {stairs} | {crouch} |")
    L += ["", "`n/a` under arms: the policy controls the arms itself. `n/a` under crouch: no height input.", "",
          "## Motion tracking", "",
          "Clips re-anchored to start at the robot. Joint error over the 23 joints all trackers control (rad); root"
          " xy and heading errors are means over the clip (final value in brackets).", "",
          "| clip | tracker | joint err | root xy err [m] | heading err [rad] | fell |", "|---|---|---|---|---|---|"]
    clips = sorted({r["test"] for r in results if r.get("kind") == "track"})
    for c in clips:
        for p in TRACKERS:
            r = by.get((p, c))
            if r is None or "error" in r:
                L.append(f"| {c} | {p} | error | | | |")
                continue
            L.append(f"| {c} ({r['seconds']} s) | {p} | {_f(r['joint_err'], 3)} | {_f(r['root_xy_err'])} "
                     f"({_f(r['root_xy_err_final'])}) | {_f(r['yaw_err'])} ({_f(r['yaw_err_final'])}) | "
                     f"{'X %.1f' % r['fall_t'] if r['fell'] else ''} |")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    from multiprocessing import Pool
    ap = argparse.ArgumentParser()
    ap.add_argument("--workers", type=int, default=12)
    ap.add_argument("--only", default=None, help="comma list of policies")
    ap.add_argument("--tests", default=None, help="comma list of tests/clips to rerun, merged into output/scorecard.json")
    a = ap.parse_args()
    J = jobs()
    if a.only:
        J = [j for j in J if j[1] in a.only.split(",")]
    if a.tests:                       # rerun some tests and merge into the existing results
        J = [j for j in J if j[2] in a.tests.split(",")]
    print(f"{len(J)} runs on {a.workers} workers", flush=True)
    res = []
    with Pool(a.workers) as pool:
        for r in pool.imap_unordered(work, J):
            res.append(r)
            print(len(res), r.get("policy"), r.get("test"), "error" if "error" in r else ("fell" if r.get("fell") else "ok"),
                  flush=True)
    os.makedirs(os.path.join(REPO, "output"), exist_ok=True)
    path = os.path.join(REPO, "output/scorecard.json")
    if (a.tests or a.only) and os.path.exists(path):
        new = {(r["policy"], r["test"]) for r in res}
        res = [r for r in json.load(open(path)) if (r["policy"], r["test"]) not in new] + res
    json.dump(res, open(os.path.join(REPO, "output/scorecard.json"), "w"), indent=1, default=float)
    open(os.path.join(REPO, "docs/SCORECARD.md"), "w").write(markdown(res))
    print("wrote docs/SCORECARD.md")
